export locale = 'en_US'
export coreUrl = 'https://squid-api.tjek.com'
export graphUrl = 'https://graph.service.shopgun.com'
export eventsTrackUrl = 'https://wolf-api.tjek.com/sync'
export eventsPulseUrl = 'wss://events.service.shopgun.com/pulse'
export assetsFileUploadUrl = 'https://assets.service.shopgun.com/upload'
